### ISSUE TITLE
Plugins within Content fields

### ISSUE THREAD

**Issue by TippyTipster** [MagicSolutions/django-cmsplugin-tabs#1]
First of all, great plugin, so thanks for the work on it! 
I am curious though if there is a way to create plugins under the content fields for each tab? Perhaps I've missed it, I am fairly new to djangocms as a whole, but so far I haven't been able to find any way to add plugins to the content fields (such as adding an image, video, or text field).

**Comment by vstoykov** [comment]
Hi @TippyTipster. We are glad that you liked the plugin. In the current state it's not possible to use other CMS plugins in the content of the tab.  This is something that other people also want but we are not figured out how to do it cleanly (because we want compatibility with Django CMS 2.4).

For now the only way of adding images or video inside tab content is with TinyMCE plugin.

**Comment by TippyTipster** [comment]
Awesome, thank you so much for letting me know @vstoykov! I will be sure to check out that plugin, keep up the great work. Thanks for pointing me in the right direction. :)

**Comment by vstoykov** [comment]
@TippyTipster There is a new test branch that can be used for django-cms v3. Now every tab is a child plugin of TabsList. You can check it if it will be helpful for you.
https://github.com/MagicSolutions/django-cmsplugin-tabs/tree/cms3
